### ISSUE TITLE
ADSE13-180 milestone

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#192]
- [x] 1. generate XTC2 data from mfxp22820 **09/08/22**
  - [x] for sample 2 (runs 1 to 24)
  - [x] for sample 4 (runs 25 to end)
  - [x] a. get Soichi's approval 
  - [x] b. transfer to NERSC (sync up with Wilko about transfer rates and methods).
  - [x] c. get runs in eLog (sync up with Murali after 09/26/22)
- [x] 2. Finalize visuals **09/07/22**
  - [x] a. Finalize automated transfer to stats folder
  - [x] b. Finalize uglymol integration
- [x] 3.  Container: **09/09/22**
  - [x] a. one size fits all: psana2, crystfel+mosflm+xds, ccp4
- [x] 4. What DAGs: **09/07/22**
  - [x] a. Just one: peak_finding > indexing > stream_analysis > merge > solve 
- [x] 5. eLog triggering must work **09/15/22**
  - [x] a. Figure out how to simulate a "live experiment" with trigger happening once data is available, run by run (see Wilko and Murali, after 09/26/22). 
- [x] 6. Draft the [report](https://docs.google.com/document/d/17Q2kohSx4kdJ6YUEp3-tGIoU0gfH6seJ/edit#heading=h.gjdgxs) **09/09/22**

**Comment by apeck12** [comment]
Regarding items 4/5 (DAGs & triggering), we'll probably need to have the stream_analysis > merge > solve portion of the pipeline triggered every time it detects indexing of a run is done (e.g. once a new r***/indexing_{tag}.summary file is written, or perhaps whenever a peak_finding > indexing task finishes?).
